---
title: "Descriptive & Inferential Analysis of a Jungian Sandplay VR Project"
subtitle: "Normality testing of patient treatment - Report"
author: "Gareth Burger &amp; James Bunt"
date: "`r format(Sys.time(), '%a, %d %B %y at %X')`"
fontsize: "10pt"
output: 
  html_document:
    toc: true
    toc_title: "Table Of Contents"
    toc_float: true
    toc_depth: 3
    fig_caption: false
    lof: true
    number_sections: true
    code_folding: hide
    theme: paper
---

```{r setup and library load, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
cat('\014')
```

# Abstract

Based on the data provided of an experiment with 149 patients (1 removed) to test the effectiveness of VR treatment on PTSD, it is reasonable to conclude that the VR treatment (both animated and static) had a positive effect on PTSD, regardless of gender.

The experiment can be deemed as reliable since we have a randomised controlled trial where participants within a pre-determined criteria (young adults aged 18-25 years old) were sourced using random sampling and randomly assigned to one of three test groups (1 control group and 2 different types of VR).

Observer reviewed test results were only considered since participant self assessments are unreliable. Results comparing the pre and post PTSD scores after VR treatment yielded a 15.01% improvement compared to the control group's improvement of 11.25% (+3.8%). Whilst all treatment provided an overall improvement, a null hypothesis that VR treatment does not impact PTSD can be rejected and an alternative hypothesis that VR treatment will result in a greater reduction in PTSD compared to traditional pyshchological therapy (control group) is suggested.

It is important to keep in mind that the above hypothesis is a prediction and not a definitive statement about the relationship between the VR treatment and reduced PTSD, but rather a starting point for further investigation where more information is needed. Whilst the data meets the assumptions required for a statistical test, it should also be noted that the experiment information available is limited which limits the reliability of findings. Specifically, the age of each participant (i.e. there maybe additional influence of age), the amount of time since diagnosis (since both HSE and Mayo Clinic advise that some PTSD can naturally reduce over time), whether the patient is receiving any potentially conflicting treatment (i.e. PTSD medication) and the time of observation (it has been noted that observations are recorded at the start and end of each day however this time of observation is not included in the data provided) can impact the reliability of the experiment which can not be validated at this time.


# Introduction

According to the HSE and Mayo Clinic (2022) Post-traumatic stress disorder (PTSD) is a mental health condition that is triggered by a terrifying event — either experiencing it or witnessing it. Symptoms may include flashbacks, nightmares and severe anxiety, as well as uncontrollable thoughts about the event (Mayo Clinic, 2022). PTSD symptoms can be physical and/ or emotional and can vary over time or vary from person to person (with or without treatment).

Treatment for PTSD can vary between psychological therapies (such as cognitive behavioural therapy - CBT) and medication (such as antidepressants). This study will only focus on the difference between traditional pyscholigical therapy (CBT) and new VR versions (animated and static) of a Jungian Sandplay  (a therapeutic method that uses sand, miniature objects, and image making within the context of the psychology of Carl Jung (Maeve Dooley, October 2018).

There are several methods employed to assess patient PTSD including observer-rated (OR), self- reported (CPSS), parental reported, and physiological measurements however only OR pre and post scores are used in this analysis due to reliability concerns of self recorded data outside a controlled and standardised manner which is essential for a robust experiment. Also note that specific focus will be applied on the variance between the pre and post scores (impact).

## Hypothesis

Null hypothesis is that VR treatments do not have a greater effect on PTSD than the control group (tranditional CBT therapy) with an alternative hypothesis that both animated and static VR treatments have a positive effect on PTSD.

One possible hypothesis test that could be used to compare the effectiveness of the different approaches used in the experiment is a two-tailed independent samples t-test. This test could be used to compare the mean change in PTSD levels (as measured by the pre-trial and post-trial CPSS and OR scores) between the Static and Animated groups, with the null hypothesis being that there is no significant difference between the two groups. This test would help determine if the use of animated VR content leads to significantly greater reductions in PTSD levels than the use of static VR content.

The study consisted of 150 patients (evenly split between male and female) divided into the groups listed below, using random sampling. A population of 149 patients were analysed (1 removed due to missing data) with 99 recieving treatment and 50 patients in the control group. All patients were young adults in the age range of 18 - 25 years however information on the exact age was not recorded but gender information was recorded. 

Note that there is no confirmation that participants are not receiving any additional treatment which can easily impact the experiment results therefore the hypothesis can not be validated

## Design

There are a few important factors that should be considered when conducting this experiment which has not been explicitly mentioned so must be considered and noted as it impacts the reliability of analysis and results.

Firstly, it is important to ensure that the study is conducted in a controlled and standardized manner. This means that the sample of patients should be selected using a random sampling method, and the groups should be of equal size to avoid any potential bias. From the information provided, since an appropriate random sampling approach has been followed, this is deemed to be appropriate and reliable however it should be noted that we have no information regarding other treatment which the patients could be involved with (since all patients have diagnosed PTSD, treatment is likely) which can directly impact the reliability of these results.

Second, studies like this should be designed to control for potential confounders, such as the patient's age, gender, and any other factors that could affect the outcome of the experiment. Gender and age is controlled within sampling which is sufficient however additional information on potentially conflicting treatment (i.e. mediciation) is not mentioned. Within the data, whilst gender is recorded, information on specific age and time of observation (i.e. start of end of day) which can impact results. 

Third, it is important that this study should use valid and reliable measures to assess the patients' PTSD levels, both at the start and end of the study therefore all self recorded (CPSS) results have been discounted since they are self reported and uncontrolled. Focusing analysis on the observer rated results (OR) will help ensure that the results of the study are accurate and unbiased so they can be compared across the different test groups.

Fourth, it should be noted that it is important to ensure that the therapists administering the treatment are trained and experienced in using the VR app, as well as in providing traditional CBT which has not been validated within the information provided. It is assumed that all patients are receiving high-quality, consistent treatment so that any differences in outcomes between the groups can be attributed to the difference in treatment type.

Finally, the study should include a sufficient number of patients to provide statistical power and to ensure that the results are statistically significant. It has been deemed that the 150 patient population (50 per treatment type) is sufficient for this analysis and will help ensure that any observed differences between the groups can be confidently attributed to the VR app rather than to chance.

# Results

81% of patients experienced improvement in their PTSD symptoms after VR treatment and overall, all test groups experienced an improvement of 13.3% median improvement (-0.72 points) which supports the hypothesis that both animated and static VR therapy reduces PTSD. VR groups reduced PTSD scores by 15.01%, this equals to 3.8% more than the control group (-0.8 compared to -0.54) whihch means that we can also reject the null hypothesis.

VR impact median reduced by -15.01%. Pre score median was 6.16 with a range of 2.06. Post score median was 5.43 with a range of 5.22.

No notable difference between VR groups was experienced (animated versus static) with a 0.49% variance in impact (between pre and post scores)

Control impact median reduced by -11.25%. Pre score median was 5.98 with a range of 4.75. Post score median was 5.31 with a range of 5.44

Gender: no notable difference between gender for those groups recieving VR Therapy (0.08 or 0.49% range in impact) however note that females were also receptive to the control experience (-12.5% impact in control compared to -15.0% in VR)

Note: 70% of the 10 participants who experienced the most impact, were males from the static VR group

*4. Provide descriptive statistics (graphs and tables) for any assumptions made.*\

## Descriptive statistics
*plots - box, bar, scatter, qq plots*

## Inferential statistics
*the inference that we are doing on our data requires that the data is normally distributed*\

## Statistical tests

## Magnitude and direction of results

*6. Determine the 95% confidence interval for the population mean of each group, and the 95% confidence interval for the difference between the means of any two groups for a variable of your choice.*\

We are 95% confident that [PE + x, PE - x] of all animated group


*7. Determine the degree of correlation between any explanatory and response variable of your choice.*\

*do student t test - see diamond quality video*


# Discussion

*5. Analyse the data to provide the hypothesis testing conclusion.*\

Outline findings and relation to the hypothesis

Limitations (if confounding variables are clearly identified by your group)


# References
- Dooley, M. (2018)
- HSE (2022). 'Post-traumatic stress disorder (PTSD)'. Available at: https://www2.hse.ie/conditions/ptsd/treatment/. Accessed on 21 December 2022.
- Mayo Clinic (2022). 'Post-traumatic stress disorder (PTSD)'. Available at: https://www.mayoclinic.org/diseases-conditions/post-traumatic-stress-disorder/symptoms-causes/syc-20355967. Accessed on 21 December 2022.
-